# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: videoclient.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='videoclient.proto',
  package='videoclient',
  syntax='proto2',
  serialized_pb=_b('\n\x11videoclient.proto\x12\x0bvideoclient\"<\n\x06Update\x12\x11\n\tupdate_id\x18\x01 \x02(\t\x12\x10\n\x08\x66ilename\x18\x02 \x02(\t\x12\r\n\x05video\x18\x03 \x02(\x0c\x42,\n\x17\x63om.example.videoclientB\x11VideoClientProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UPDATE = _descriptor.Descriptor(
  name='Update',
  full_name='videoclient.Update',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='update_id', full_name='videoclient.Update.update_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filename', full_name='videoclient.Update.filename', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='video', full_name='videoclient.Update.video', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['Update'] = _UPDATE

Update = _reflection.GeneratedProtocolMessageType('Update', (_message.Message,), dict(
  DESCRIPTOR = _UPDATE,
  __module__ = 'videoclient_pb2'
  # @@protoc_insertion_point(class_scope:videoclient.Update)
  ))
_sym_db.RegisterMessage(Update)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\027com.example.videoclientB\021VideoClientProtos'))
# @@protoc_insertion_point(module_scope)
